repositories {
    mavenCentral()
}

dependencies {
    implementation libs.q4j.config
    implementation libs.q4j.testng
    implementation libs.q4j.sql
    implementation libs.q4j.tyrus
    implementation libs.q4j.selenide
    implementation libs.q4j.rest.assured
    implementation libs.q4j.jackson.json
    testImplementation libs.testng
    testRuntimeOnly libs.postgresql
    checkstyle libs.checkstyle
}
