_commit: v2.21.6
_src_path: https://github.com/quokkify/project-toolkit.git
allure_report: true
components:
  - type: node
    path: .
docker: true
project_name: MarketDesk
release_please: true
renovate: true
renovate_config_repository: quokkify/renovate-presets
renovate_presets:
  - default
  - github-actions
  - javascript
  - docker
toolkit_version: v2.21.6
